# Generated by Django 6.0.3 on 2026-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='backordered_qty',
            field=models.IntegerField(default=0),
        ),
    ]
