# Generated by Django 6.0.3 on 2026-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorderitem_backordered_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='deducted_qty',
            field=models.IntegerField(default=0),
        ),
    ]
