# Generated by Django 6.0.3 on 2026-03-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BacklogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_item_id', models.IntegerField()),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_on_backlog', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='inventory_manager.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
