# Generated by Django 6.0.3 on 2026-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0002_purchaseorder_auto_generated_backlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogentry',
            name='sales_order_id',
            field=models.IntegerField(default=0),
        ),
    ]
